spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/si_local'
    username: 'app'
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
app:
  jwtSecret: "secret_key"
  jwtExpirationInMs: 604800000
